Add the idea of UI pipeline for deforestation prediction model
moja-global/mentorship pull request #23
Opened 2022-04-06 22:25 UTC by govarun

2022-04-09 09:53 UTC, HarshCasper requested changes

2022-04-09 09:53 UTC, HarshCasper commented on google-summer-of-code/GSOC-2022-Ideas.md
> +Get started by reading and understanding the problem statement and our approach on our github repository. Then try to go through the code base and see for possible improvements if you can. If you spo
Right now the GitHub repository is pretty much empty. How about directing them to the case study here: https://community.moja.global/case-studies/powering-deforestation-prediction-using-artificial-intelligence

2022-04-09 09:53 UTC, HarshCasper commented on google-summer-of-code/GSOC-2022-Ideas.md
> +Experience in implementing websites and connecting them to a backend python server is a must. Understanding of Python is needed too. Otherwise the choice of UI library/tools is flexible and will be b
Do you have any particular Python web framework in mind? Like Flask, FastAPI or Django?

2022-04-10 19:41 UTC, merged

2022-04-11 11:09 UTC, WhiteBear1611 commented
Hello @govarun, I am interested in working on this project and I already have prior knowledge on Python and Flask which will be very helpful for completing first 2 goals of 1) web based app for model interaction and 2) providing user with the model output.